# Generated by Django 4.0.4 on 2022-05-30 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.BigIntegerField(null=True)),
                ('mobile_no', models.BigIntegerField()),
                ('unit_no', models.IntegerField()),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('billing_add_1', models.CharField(max_length=100)),
                ('delivery_add_2', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=20, null=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('bank_acc_no', models.BigIntegerField()),
                ('nric_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('address_doc_type', models.CharField(choices=[('DOC1', 'DOC1')], max_length=50, null=True)),
                ('address_doc_no', models.IntegerField(null=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
