# Generated by Django 4.0.4 on 2022-05-30 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='address_doc_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='nric_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
