# Generated by Django 4.0.4 on 2022-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_customer_delete_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forgot_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
