# Generated by Django 4.0.4 on 2022-05-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_customer_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
