# Generated by Django 4.0.4 on 2022-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_customer_forgot_password_token_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='expired_on',
            field=models.DateTimeField(null=True),
        ),
    ]
