# Generated by Django 4.0.4 on 2022-05-31 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_resetpassword_expired_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPassword',
            new_name='ResetPasswordOTP',
        ),
    ]
