# Generated by Django 4.0.4 on 2022-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_customeraddress_customer_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
            ],
        ),
    ]
