# Generated by Django 4.0.4 on 2022-06-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
