# Generated by Django 4.0.4 on 2022-06-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_customer_addresses_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpasswordotp',
            old_name='otp',
            new_name='token',
        ),
    ]
