# Generated by Django 4.0.4 on 2022-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_rename_otp_resetpasswordotp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordotp',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
