# Generated by Django 4.0.4 on 2022-06-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_customer_is_approved_customer_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
