# Generated by Django 4.0.4 on 2022-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_customer_nric_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='country', max_length=100),
            preserve_default=False,
        ),
    ]
