# Generated by Django 4.0.4 on 2022-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_remove_customeraddress_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='day',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='month',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/profile/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
