# Generated by Django 4.0.4 on 2022-06-04 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0010_customeraddress_customer_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.BigIntegerField(blank=True, null=True)),
                ('mobile_no', models.BigIntegerField()),
                ('unit_no', models.IntegerField(blank=True, null=True)),
                ('address_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_add_1', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_add_2', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_acc_no', models.BigIntegerField(blank=True, null=True)),
                ('nric_no', models.BigIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('address_doc_type', models.CharField(blank=True, choices=[('DOC1', 'DOC1')], max_length=50, null=True)),
                ('address_doc_no', models.BigIntegerField(blank=True, null=True)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.country')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
