# Generated by Django 4.0.4 on 2022-06-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
